version: "3.7"
services:
  sparql-endpoint:
    environment: 
      PORT: 1234
    ports:
      - "3001:1234"
    build:
      context: ./sparql-endpoint
      args:
        DBA_PASSWORD: abcd
  web:
    environment: 
      PORT: 1234
    ports:
      - "3000:1234"
    build:
      context: ./web
      args:
        SPARQL_ENDPOINT_URL: http://sparql-endpoint:1234/sparql

