version: "3.7"
services:
  sparql-endpoint:
    environment: 
      PORT: 1234
    ports:
      - "3001:1234"
    build: ./sparql-endpoint
  web:
    environment: 
      PORT: 1234
    ports:
      - "3000:1234"
    build: ./web
